#!/usr/bin/env python3
"""Generate SCENES.md — every scene in the deck, its URL, and the script it came from.

One row per scene, in deck order: the counter number, the title, the URL that deep-links
it, the pen and layers it draws, and the paragraph of docs/script_v3.md that the beat's
counter mark sits in. That last column is the point — it puts the original narration next
to the shot it belongs to, so a take can be checked against what was actually written.

The deck order is read from the RUNNING APP, not re-derived here. Fourteen choreographed
sequences are spliced into the 93 counter beats by scenes.ts, and a second implementation
of that splice in Python is a second thing to be wrong — an index that disagrees with the
deck is worse than no index. So this drives the dev server, asks it for `window.__deck()`,
and writes down what the deck says it is.

The script pairing is by counter mark. docs/script_v3.md carries 93 of them written as
U+27E8 n U+27E9, one per beat, and the paragraph containing the mark is the narration for
that beat. Choreographed scenes carry no mark of their own, so they inherit the paragraph
of the beat they follow and are labelled as such rather than left blank.

Usage:
    cd app && npm run dev &
    python3 scripts/scene_index.py
    python3 scripts/scene_index.py --url http://localhost:5174/
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "docs" / "script_v3.md"
OUT = ROOT / "SCENES.md"

MARK = re.compile(r"⟨(\d+)⟩")

PEN_LABEL = {
    "congress": "Congress",
    "statisticians": "The statisticians",
    "politicians": "The politicians",
    "courts": "The courts",
    "markets": "The markets",
    "surveyors": "The surveyors",
}

CHAPTER_LABEL = {
    "cold-open": "Cold open",
    "why": "Why this?",
    "no-map-dept": "There is no map department",
    "six-pens": "Problem number one, and the six pens",
    "tier-1": "Tier 1: the obvious ones",
    "count-you": "The layers that count you",
    "political": "The political layers",
    "legal": "The legal layers",
    "rung-5": "Rung 5: the market and machine layers",
    "swarm": "Rung 6: the swarm",
    "reveal": "The reveal",
    "human-turn": "The human turn",
    "close": "Callback close",
}


def script_paragraphs() -> dict[int, str]:
    """The paragraph each counter mark sits in, keyed by beat number.

    Paragraphs are blank-line separated. The mark itself is stripped out — it is a
    production cue, not narration — and stage directions in [square brackets] are kept,
    because they say what the shot was meant to be.
    """
    if not SCRIPT.exists():
        raise FileNotFoundError(f"no script at {SCRIPT.relative_to(ROOT)}")
    text = SCRIPT.read_text()
    out: dict[int, str] = {}
    for para in re.split(r"\n\s*\n", text):
        marks = MARK.findall(para)
        if not marks:
            continue
        clean = MARK.sub("", para).strip()
        clean = re.sub(r"[ \t]+", " ", clean)
        clean = re.sub(r"\s+\n", "\n", clean)
        for m in marks:
            # A paragraph carrying two marks is the narration for both.
            out[int(m)] = clean
    return out


def fetch_deck(url: str) -> list[dict]:
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        b = p.chromium.launch(channel="chrome")
        pg = b.new_page(viewport={"width": 1280, "height": 720})
        pg.goto(url, wait_until="load")
        pg.wait_for_function("() => window.__deck", timeout=30000)
        deck = pg.evaluate("() => window.__deck()")
        b.close()
    return deck


def title_of(row: dict) -> str:
    """What to call the scene: its card, else its caption, else its id."""
    return row["card"] or row["caption"] or row["id"]


def render(deck: list[dict], paras: dict[int, str]) -> str:
    L: list[str] = []
    A = L.append

    A("# Scenes")
    A("")
    A(f"Every scene in the deck, in order: {len(deck)} of them — a two-part cold open, the "
      "93 counter beats, and 14")
    A("choreographed sequences spliced in at their script positions.")
    A("")
    A("Each entry carries the URL that deep-links it, what it draws, and the paragraph of")
    A("`docs/script_v3.md` the beat's counter mark sits in. Replace `localhost:5173` with "
      "your")
    A("deployment host and every link works unchanged.")
    A("")
    A("Generated by `scripts/scene_index.py` from the running deck — don't hand-edit.")
    A("")
    A("## Index")
    A("")
    A("| # | counter | scene | URL |")
    A("|---:|---:|---|---|")
    for row in deck:
        n = row["counter"]
        counter = "" if n is None else ("blur" if n == "blur" else str(n))
        A(f"| {row['i'] + 1} | {counter} | {title_of(row)} | "
          f"[`?scene={row['id']}`](http://localhost:5173/?scene={row['id']}) |")
    A("")
    A("---")
    A("")

    last_chapter = None
    last_beat = 0
    for row in deck:
        chapter = row["chapter"]
        if chapter != last_chapter:
            A(f"## {CHAPTER_LABEL.get(chapter, chapter)}")
            A("")
            last_chapter = chapter

        beat = row["beat"]
        if beat:
            last_beat = beat
        n = row["counter"]
        counter = "—" if n is None else ("000" if n == "blur" else str(n))

        A(f"### {counter} · {title_of(row)}")
        A("")
        A(f"<http://localhost:5173/?scene={row['id']}>")
        A("")

        facts = [f"`{row['id']}`"]
        if row["pen"]:
            facts.append(PEN_LABEL.get(row["pen"], row["pen"]))
        if row["layers"]:
            facts.append(", ".join(f"`{x}`" for x in row["layers"]))
        else:
            facts.append("no geometry — a typographic card")
        if row["steps"]:
            facts.append(f"{row['steps']}-step choreography")
        A("  ·  ".join(facts))
        A("")

        if row["caption"]:
            A(f"**On screen:** {row['caption']}")
            A("")
        if row["card"]:
            sub = f" — {row['cardSub']}" if row["cardSub"] else ""
            A(f"**Card:** {row['card']}{sub}")
            A("")

        para = paras.get(beat) if beat else None
        if para:
            A("**Script:**")
            A("")
            for line in para.splitlines():
                A(f"> {line}" if line.strip() else ">")
            A("")
        elif beat:
            A(f"*No counter mark ⟨{beat}⟩ found in the script.*")
            A("")
        else:
            inherited = paras.get(last_beat)
            if inherited and row["i"] > 1:
                A(f"**Script** — no counter mark of its own; this sequence is spliced in "
                  f"after beat {last_beat}:")
                A("")
                for line in inherited.splitlines():
                    A(f"> {line}" if line.strip() else ">")
                A("")
            else:
                A("*Runs before the counter starts.*")
                A("")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--url", default="http://localhost:5173/",
                    help="a running dev server (default: %(default)s)")
    args = ap.parse_args()

    try:
        paras = script_paragraphs()
    except FileNotFoundError as e:
        print(f"FAILED — {e}")
        return 1

    try:
        deck = fetch_deck(args.url)
    except Exception as e:
        print(f"FAILED — could not read the deck from {args.url}: {type(e).__name__}: {e}")
        print("        start it with: cd app && npm run dev")
        return 1

    OUT.write_text(render(deck, paras))

    beats = [r for r in deck if r["beat"]]
    matched = sum(1 for r in beats if r["beat"] in paras)
    print(f"  {len(deck)} scenes, {len(beats)} with a counter beat")
    print(f"  script paragraphs found for {matched} of {len(beats)}")
    print(f"  {len(paras)} counter marks in {SCRIPT.relative_to(ROOT)}")
    missing = sorted({r["beat"] for r in beats if r["beat"] not in paras})
    if missing:
        print(f"  NO SCRIPT TEXT for beats: {missing}")
    print(f"  wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
